import type { SchoolCompareResponse } from "../../api/types";

export const COMPARE_RESPONSE: SchoolCompareResponse = {
  access: {
    state: "available",
    capability_key: "premium_comparison",
    reason_code: null,
    product_codes: [],
    requires_auth: false,
    requires_purchase: false,
    school_name: null,
  },
  schools: [
    {
      urn: "100001",
      name: "Primary Example",
      postcode: "SW1A 1AA",
      phase: "Primary",
      type: "Community school",
      age_range_label: "Ages 4-11",
    },
    {
      urn: "200002",
      name: "Secondary Example",
      postcode: "SW1A 2BB",
      phase: "Secondary",
      type: "Academy sponsor led",
      age_range_label: "Ages 11-18",
    },
  ],
  sections: [
    {
      key: "inspection",
      label: "Inspection",
      rows: [
        {
          metric_key: "ofsted_overall_effectiveness",
          label: "Latest Ofsted",
          unit: "text",
          cells: [
            {
              urn: "100001",
              value_text: "Good",
              value_numeric: null,
              year_label: null,
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
            {
              urn: "200002",
              value_text: "Requires improvement",
              value_numeric: null,
              year_label: null,
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
          ],
        },
        {
          metric_key: "most_recent_inspection_date",
          label: "Most recent inspection",
          unit: "date",
          cells: [
            {
              urn: "100001",
              value_text: "10 Oct 2025",
              value_numeric: null,
              year_label: null,
              snapshot_date: "2025-10-10",
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
            {
              urn: "200002",
              value_text: "4 Nov 2025",
              value_numeric: null,
              year_label: null,
              snapshot_date: "2025-11-04",
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
          ],
        },
      ],
    },
    {
      key: "demographics",
      label: "Demographics",
      rows: [
        {
          metric_key: "fsm_pct",
          label: "Free School Meals",
          unit: "percent",
          cells: [
            {
              urn: "100001",
              value_text: "20.1%",
              value_numeric: 20.1,
              year_label: "2024/25",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: {
                academic_year: "2024/25",
                school_value: 20.1,
                national_value: 18.0,
                local_value: 19.2,
                school_vs_national_delta: 2.1,
                school_vs_local_delta: 0.9,
                local_scope: "local_authority_district",
                local_area_code: "E09000033",
                local_area_label: "Westminster",
                contexts: [],
              },
            },
            {
              urn: "200002",
              value_text: null,
              value_numeric: null,
              year_label: null,
              snapshot_date: null,
              availability: "unsupported",
              completeness_status: "unavailable",
              completeness_reason_code: "not_applicable",
              benchmark: null,
            },
          ],
        },
      ],
    },
    {
      key: "finance",
      label: "Finance",
      rows: [
        {
          metric_key: "total_income_gbp",
          label: "Total Income",
          unit: "currency",
          cells: [
            {
              urn: "100001",
              value_text: "£1.2m",
              value_numeric: 1200000,
              year_label: "2023/24",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
            {
              urn: "200002",
              value_text: "£5.8m",
              value_numeric: 5800000,
              year_label: "2023/24",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
          ],
        },
        {
          metric_key: "finance_income_per_pupil_gbp",
          label: "Income Per Pupil",
          unit: "currency",
          cells: [
            {
              urn: "100001",
              value_text: "£6k",
              value_numeric: 6000,
              year_label: "2023/24",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: {
                academic_year: "2023/24",
                school_value: 6000,
                national_value: 5800,
                local_value: 6200,
                school_vs_national_delta: 200,
                school_vs_local_delta: -200,
                local_scope: "local_authority_district",
                local_area_code: "E09000033",
                local_area_label: "Westminster",
                contexts: [],
              },
            },
            {
              urn: "200002",
              value_text: "£7k",
              value_numeric: 7000,
              year_label: "2023/24",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: {
                academic_year: "2023/24",
                school_value: 7000,
                national_value: 5800,
                local_value: 6500,
                school_vs_national_delta: 1200,
                school_vs_local_delta: 500,
                local_scope: "local_authority_district",
                local_area_code: "E09000033",
                local_area_label: "Westminster",
                contexts: [],
              },
            },
          ],
        },
      ],
    },
    {
      key: "admissions",
      label: "Admissions",
      rows: [
        {
          metric_key: "admissions_places_offered",
          label: "Places Offered",
          unit: "count",
          cells: [
            {
              urn: "100001",
              value_text: "60",
              value_numeric: 60,
              year_label: "2024/25",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
            {
              urn: "200002",
              value_text: "180",
              value_numeric: 180,
              year_label: "2024/25",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
          ],
        },
      ],
    },
    {
      key: "destinations",
      label: "Destinations",
      rows: [
        {
          metric_key: "destinations_ks4_overall_pct",
          label: "KS4 Sustained Destinations",
          unit: "percent",
          cells: [
            {
              urn: "100001",
              value_text: null,
              value_numeric: null,
              year_label: null,
              snapshot_date: null,
              availability: "unsupported",
              completeness_status: "unavailable",
              completeness_reason_code: "not_applicable",
              benchmark: null,
            },
            {
              urn: "200002",
              value_text: "92.0%",
              value_numeric: 92.0,
              year_label: "2022/23",
              snapshot_date: null,
              availability: "available",
              completeness_status: "available",
              completeness_reason_code: null,
              benchmark: null,
            },
          ],
        },
      ],
    },
    {
      key: "area",
      label: "Area",
      rows: [
        {
          metric_key: "area_crime_incidents_per_1000",
          label: "Crime incidents per 1,000",
          unit: "rate",
          cells: [
            {
              urn: "100001",
              value_text: "120.00",
              value_numeric: 120,
              year_label: "2025",
              snapshot_date: null,
              availability: "available",
              completeness_status: "partial",
              completeness_reason_code: "source_coverage_gap",
              benchmark: null,
            },
            {
              urn: "200002",
              value_text: null,
              value_numeric: null,
              year_label: null,
              snapshot_date: null,
              availability: "unavailable",
              completeness_status: "unavailable",
              completeness_reason_code: "source_coverage_gap",
              benchmark: null,
            },
          ],
        },
      ],
    },
  ],
};
