from dataclasses import dataclass
from typing import Literal

from civitas.domain.school_profiles.models import (
    SectionCompletenessReasonCode,
    SectionCompletenessStatus,
)

CompareSectionKey = Literal[
    "inspection",
    "demographics",
    "attendance",
    "behaviour",
    "workforce",
    "finance",
    "performance",
    "admissions",
    "destinations",
    "area",
]
CompareMetricUnit = Literal[
    "text",
    "date",
    "days",
    "years",
    "percent",
    "count",
    "rate",
    "ratio",
    "score",
    "currency",
    "decile",
]
CompareAvailability = Literal["available", "unsupported", "unavailable", "suppressed"]
ComparePerformanceGroup = Literal["ks2", "ks4"]
CompareCompletenessKey = Literal[
    "demographics",
    "attendance",
    "behaviour",
    "workforce",
    "finance",
    "leadership",
    "performance",
    "admissions",
    "destinations",
    "ofsted_latest",
    "area_deprivation",
    "area_crime",
    "area_house_prices",
]
CompareCompletenessStatus = SectionCompletenessStatus
CompareCompletenessReasonCode = SectionCompletenessReasonCode


@dataclass(frozen=True)
class CompareMetricDefinition:
    metric_key: str
    label: str
    unit: CompareMetricUnit
    section_key: CompareSectionKey
    completeness_key: CompareCompletenessKey
    benchmark_supported: bool
    decimals: int | None = None
    performance_group: ComparePerformanceGroup | None = None


COMPARE_SECTION_ORDER: tuple[CompareSectionKey, ...] = (
    "inspection",
    "demographics",
    "attendance",
    "behaviour",
    "workforce",
    "finance",
    "performance",
    "admissions",
    "destinations",
    "area",
)

COMPARE_SECTION_LABELS: dict[CompareSectionKey, str] = {
    "inspection": "Inspection",
    "demographics": "Demographics",
    "attendance": "Attendance",
    "behaviour": "Behaviour",
    "workforce": "Workforce",
    "finance": "Finance",
    "performance": "Performance",
    "admissions": "Admissions",
    "destinations": "Destinations",
    "area": "Area",
}

COMPARE_METRIC_CATALOG: tuple[CompareMetricDefinition, ...] = (
    CompareMetricDefinition(
        metric_key="ofsted_overall_effectiveness",
        label="Latest Ofsted",
        unit="text",
        section_key="inspection",
        completeness_key="ofsted_latest",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="most_recent_inspection_date",
        label="Most recent inspection",
        unit="date",
        section_key="inspection",
        completeness_key="ofsted_latest",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="days_since_most_recent_inspection",
        label="Time since inspection",
        unit="days",
        section_key="inspection",
        completeness_key="ofsted_latest",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="disadvantaged_pct",
        label="Disadvantaged pupils",
        unit="percent",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="fsm_pct",
        label="Free School Meals",
        unit="percent",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="fsm6_pct",
        label="FSM6",
        unit="percent",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="sen_pct",
        label="SEN support",
        unit="percent",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="ehcp_pct",
        label="EHCP",
        unit="percent",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="eal_pct",
        label="EAL",
        unit="percent",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="ethnicity_summary",
        label="Ethnicity summary",
        unit="text",
        section_key="demographics",
        completeness_key="demographics",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="overall_attendance_pct",
        label="Overall attendance",
        unit="percent",
        section_key="attendance",
        completeness_key="attendance",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="overall_absence_pct",
        label="Overall absence",
        unit="percent",
        section_key="attendance",
        completeness_key="attendance",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="persistent_absence_pct",
        label="Persistent absence",
        unit="percent",
        section_key="attendance",
        completeness_key="attendance",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="suspensions_count",
        label="Suspensions",
        unit="count",
        section_key="behaviour",
        completeness_key="behaviour",
        benchmark_supported=True,
    ),
    CompareMetricDefinition(
        metric_key="suspensions_rate",
        label="Suspensions rate",
        unit="rate",
        section_key="behaviour",
        completeness_key="behaviour",
        benchmark_supported=True,
        decimals=2,
    ),
    CompareMetricDefinition(
        metric_key="permanent_exclusions_count",
        label="Permanent exclusions",
        unit="count",
        section_key="behaviour",
        completeness_key="behaviour",
        benchmark_supported=True,
    ),
    CompareMetricDefinition(
        metric_key="permanent_exclusions_rate",
        label="Permanent exclusions rate",
        unit="rate",
        section_key="behaviour",
        completeness_key="behaviour",
        benchmark_supported=True,
        decimals=2,
    ),
    CompareMetricDefinition(
        metric_key="pupil_teacher_ratio",
        label="Pupil to teacher ratio",
        unit="ratio",
        section_key="workforce",
        completeness_key="workforce",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="supply_staff_pct",
        label="Supply staff",
        unit="percent",
        section_key="workforce",
        completeness_key="workforce",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="qts_pct",
        label="Qualified Teacher Status",
        unit="percent",
        section_key="workforce",
        completeness_key="workforce",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="headteacher_name",
        label="Headteacher",
        unit="text",
        section_key="workforce",
        completeness_key="leadership",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="headteacher_tenure_years",
        label="Headteacher tenure",
        unit="years",
        section_key="workforce",
        completeness_key="leadership",
        benchmark_supported=False,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="total_income_gbp",
        label="Total Income",
        unit="currency",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="total_expenditure_gbp",
        label="Total Expenditure",
        unit="currency",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="in_year_balance_gbp",
        label="In-Year Balance",
        unit="currency",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="finance_income_per_pupil_gbp",
        label="Income Per Pupil",
        unit="currency",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=True,
    ),
    CompareMetricDefinition(
        metric_key="finance_expenditure_per_pupil_gbp",
        label="Expenditure Per Pupil",
        unit="currency",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=True,
    ),
    CompareMetricDefinition(
        metric_key="finance_staff_costs_pct_of_expenditure",
        label="Staff Costs % of Expenditure",
        unit="percent",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="finance_revenue_reserve_per_pupil_gbp",
        label="Revenue Reserve Per Pupil",
        unit="currency",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=True,
    ),
    CompareMetricDefinition(
        metric_key="finance_supply_staff_costs_pct_of_staff_costs",
        label="Supply Staff Costs % of Staff Costs",
        unit="percent",
        section_key="finance",
        completeness_key="finance",
        benchmark_supported=True,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="ks2_reading_expected_pct",
        label="KS2 reading expected",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=False,
        decimals=1,
        performance_group="ks2",
    ),
    CompareMetricDefinition(
        metric_key="ks2_writing_expected_pct",
        label="KS2 writing expected",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=False,
        decimals=1,
        performance_group="ks2",
    ),
    CompareMetricDefinition(
        metric_key="ks2_maths_expected_pct",
        label="KS2 maths expected",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=False,
        decimals=1,
        performance_group="ks2",
    ),
    CompareMetricDefinition(
        metric_key="ks2_combined_expected_pct",
        label="KS2 combined expected",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=False,
        decimals=1,
        performance_group="ks2",
    ),
    CompareMetricDefinition(
        metric_key="ks2_combined_higher_pct",
        label="KS2 combined higher",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=False,
        decimals=1,
        performance_group="ks2",
    ),
    CompareMetricDefinition(
        metric_key="attainment8_average",
        label="Attainment 8",
        unit="score",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=True,
        decimals=1,
        performance_group="ks4",
    ),
    CompareMetricDefinition(
        metric_key="progress8_average",
        label="Progress 8",
        unit="score",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=True,
        decimals=2,
        performance_group="ks4",
    ),
    CompareMetricDefinition(
        metric_key="progress8_disadvantaged_gap",
        label="Progress 8 disadvantaged gap",
        unit="score",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=True,
        decimals=2,
        performance_group="ks4",
    ),
    CompareMetricDefinition(
        metric_key="engmath_5_plus_pct",
        label="English and Maths grade 5+",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=True,
        decimals=1,
        performance_group="ks4",
    ),
    CompareMetricDefinition(
        metric_key="ebacc_entry_pct",
        label="EBacc entry",
        unit="percent",
        section_key="performance",
        completeness_key="performance",
        benchmark_supported=True,
        decimals=1,
        performance_group="ks4",
    ),
    # ── Admissions ──────────────────────────────────────────────────────
    CompareMetricDefinition(
        metric_key="admissions_places_offered",
        label="Places Offered",
        unit="count",
        section_key="admissions",
        completeness_key="admissions",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="admissions_applications_first_preference",
        label="First Preference Applications",
        unit="count",
        section_key="admissions",
        completeness_key="admissions",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="admissions_applications_any_preference",
        label="All Applications",
        unit="count",
        section_key="admissions",
        completeness_key="admissions",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="admissions_oversubscription_ratio",
        label="Oversubscription Ratio",
        unit="ratio",
        section_key="admissions",
        completeness_key="admissions",
        benchmark_supported=False,
        decimals=2,
    ),
    CompareMetricDefinition(
        metric_key="admissions_first_preference_offer_rate",
        label="First Preference Offer Rate",
        unit="percent",
        section_key="admissions",
        completeness_key="admissions",
        benchmark_supported=False,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="admissions_policy",
        label="Admissions Policy",
        unit="text",
        section_key="admissions",
        completeness_key="admissions",
        benchmark_supported=False,
    ),
    # ── Destinations ──────────────────────────────────────────────────
    CompareMetricDefinition(
        metric_key="destinations_ks4_overall_pct",
        label="KS4 Sustained Destinations",
        unit="percent",
        section_key="destinations",
        completeness_key="destinations",
        benchmark_supported=False,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="destinations_ks4_education_pct",
        label="KS4 Education",
        unit="percent",
        section_key="destinations",
        completeness_key="destinations",
        benchmark_supported=False,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="destinations_ks4_apprenticeship_pct",
        label="KS4 Apprenticeship",
        unit="percent",
        section_key="destinations",
        completeness_key="destinations",
        benchmark_supported=False,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="destinations_ks4_employment_pct",
        label="KS4 Employment",
        unit="percent",
        section_key="destinations",
        completeness_key="destinations",
        benchmark_supported=False,
        decimals=1,
    ),
    CompareMetricDefinition(
        metric_key="destinations_ks4_not_sustained_pct",
        label="KS4 Not Sustained",
        unit="percent",
        section_key="destinations",
        completeness_key="destinations",
        benchmark_supported=False,
        decimals=1,
    ),
    # ── Area ──────────────────────────────────────────────────────────
    CompareMetricDefinition(
        metric_key="imd_decile",
        label="IMD decile",
        unit="decile",
        section_key="area",
        completeness_key="area_deprivation",
        benchmark_supported=False,
    ),
    CompareMetricDefinition(
        metric_key="area_crime_incidents_per_1000",
        label="Crime incidents per 1,000",
        unit="rate",
        section_key="area",
        completeness_key="area_crime",
        benchmark_supported=True,
        decimals=2,
    ),
    CompareMetricDefinition(
        metric_key="area_house_price_average",
        label="Average house price",
        unit="currency",
        section_key="area",
        completeness_key="area_house_prices",
        benchmark_supported=True,
    ),
    CompareMetricDefinition(
        metric_key="area_house_price_annual_change_pct",
        label="House price annual change",
        unit="percent",
        section_key="area",
        completeness_key="area_house_prices",
        benchmark_supported=True,
        decimals=1,
    ),
)
