/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Schools */
        get: operations["search_schools_api_v1_schools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Schools By Name */
        get: operations["search_schools_by_name_api_v1_schools_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{urn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get School Profile */
        get: operations["get_school_profile_api_v1_schools__urn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{urn}/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get School Trends */
        get: operations["get_school_trends_api_v1_schools__urn__trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SchoolNameSearchResponse */
        SchoolNameSearchResponse: {
            /** Count */
            count: number;
            /** Schools */
            schools: components["schemas"]["SchoolSearchItemResponse"][];
        };
        /** SchoolProfileAreaContextCoverageResponse */
        SchoolProfileAreaContextCoverageResponse: {
            /** Has Deprivation */
            has_deprivation: boolean;
            /** Has Crime */
            has_crime: boolean;
            /** Crime Months Available */
            crime_months_available: number;
        };
        /** SchoolProfileAreaContextResponse */
        SchoolProfileAreaContextResponse: {
            deprivation: components["schemas"]["SchoolProfileAreaDeprivationResponse"] | null;
            crime: components["schemas"]["SchoolProfileAreaCrimeResponse"] | null;
            coverage: components["schemas"]["SchoolProfileAreaContextCoverageResponse"];
        };
        /** SchoolProfileAreaCrimeCategoryResponse */
        SchoolProfileAreaCrimeCategoryResponse: {
            /** Category */
            category: string;
            /** Incident Count */
            incident_count: number;
        };
        /** SchoolProfileAreaCrimeResponse */
        SchoolProfileAreaCrimeResponse: {
            /** Radius Miles */
            radius_miles: number;
            /** Latest Month */
            latest_month: string;
            /** Total Incidents */
            total_incidents: number;
            /** Categories */
            categories: components["schemas"]["SchoolProfileAreaCrimeCategoryResponse"][];
        };
        /** SchoolProfileAreaDeprivationResponse */
        SchoolProfileAreaDeprivationResponse: {
            /** Lsoa Code */
            lsoa_code: string;
            /** Imd Score */
            imd_score: number;
            /** Imd Rank */
            imd_rank: number;
            /** Imd Decile */
            imd_decile: number;
            /** Idaci Score */
            idaci_score: number;
            /** Idaci Decile */
            idaci_decile: number;
            /** Source Release */
            source_release: string;
        };
        /** SchoolProfileCompletenessResponse */
        SchoolProfileCompletenessResponse: {
            demographics: components["schemas"]["SchoolProfileSectionCompletenessResponse"];
            performance: components["schemas"]["SchoolProfileSectionCompletenessResponse"];
            ofsted_latest: components["schemas"]["SchoolProfileSectionCompletenessResponse"];
            ofsted_timeline: components["schemas"]["SchoolProfileSectionCompletenessResponse"];
            area_deprivation: components["schemas"]["SchoolProfileSectionCompletenessResponse"];
            area_crime: components["schemas"]["SchoolProfileSectionCompletenessResponse"];
        };
        /** SchoolProfileDemographicsCoverageResponse */
        SchoolProfileDemographicsCoverageResponse: {
            /** Fsm Supported */
            fsm_supported: boolean;
            /** Ethnicity Supported */
            ethnicity_supported: boolean;
            /** Top Languages Supported */
            top_languages_supported: boolean;
        };
        /** SchoolProfileDemographicsEthnicityGroupResponse */
        SchoolProfileDemographicsEthnicityGroupResponse: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Percentage */
            percentage: number | null;
            /** Count */
            count: number | null;
        };
        /** SchoolProfileDemographicsLatestResponse */
        SchoolProfileDemographicsLatestResponse: {
            /** Academic Year */
            academic_year: string;
            /** Disadvantaged Pct */
            disadvantaged_pct: number | null;
            /** Fsm Pct */
            fsm_pct: number | null;
            /** Sen Pct */
            sen_pct: number | null;
            /** Ehcp Pct */
            ehcp_pct: number | null;
            /** Eal Pct */
            eal_pct: number | null;
            /** First Language English Pct */
            first_language_english_pct: number | null;
            /** First Language Unclassified Pct */
            first_language_unclassified_pct: number | null;
            coverage: components["schemas"]["SchoolProfileDemographicsCoverageResponse"];
            /** Ethnicity Breakdown */
            ethnicity_breakdown?: components["schemas"]["SchoolProfileDemographicsEthnicityGroupResponse"][];
        };
        /** SchoolProfileOfstedLatestResponse */
        SchoolProfileOfstedLatestResponse: {
            /** Overall Effectiveness Code */
            overall_effectiveness_code: string | null;
            /** Overall Effectiveness Label */
            overall_effectiveness_label: string | null;
            /** Inspection Start Date */
            inspection_start_date: string | null;
            /** Publication Date */
            publication_date: string | null;
            /** Latest Oeif Inspection Start Date */
            latest_oeif_inspection_start_date: string | null;
            /** Latest Oeif Publication Date */
            latest_oeif_publication_date: string | null;
            /** Quality Of Education Code */
            quality_of_education_code: string | null;
            /** Quality Of Education Label */
            quality_of_education_label: string | null;
            /** Behaviour And Attitudes Code */
            behaviour_and_attitudes_code: string | null;
            /** Behaviour And Attitudes Label */
            behaviour_and_attitudes_label: string | null;
            /** Personal Development Code */
            personal_development_code: string | null;
            /** Personal Development Label */
            personal_development_label: string | null;
            /** Leadership And Management Code */
            leadership_and_management_code: string | null;
            /** Leadership And Management Label */
            leadership_and_management_label: string | null;
            /** Latest Ungraded Inspection Date */
            latest_ungraded_inspection_date: string | null;
            /** Latest Ungraded Publication Date */
            latest_ungraded_publication_date: string | null;
            /** Most Recent Inspection Date */
            most_recent_inspection_date: string | null;
            /** Days Since Most Recent Inspection */
            days_since_most_recent_inspection: number | null;
            /** Is Graded */
            is_graded: boolean;
            /** Ungraded Outcome */
            ungraded_outcome: string | null;
        };
        /** SchoolProfileOfstedTimelineCoverageResponse */
        SchoolProfileOfstedTimelineCoverageResponse: {
            /** Is Partial History */
            is_partial_history: boolean;
            /** Earliest Event Date */
            earliest_event_date: string | null;
            /** Latest Event Date */
            latest_event_date: string | null;
            /** Events Count */
            events_count: number;
        };
        /** SchoolProfileOfstedTimelineEventResponse */
        SchoolProfileOfstedTimelineEventResponse: {
            /** Inspection Number */
            inspection_number: string;
            /**
             * Inspection Start Date
             * Format: date
             */
            inspection_start_date: string;
            /** Publication Date */
            publication_date: string | null;
            /** Inspection Type */
            inspection_type: string | null;
            /** Overall Effectiveness Label */
            overall_effectiveness_label: string | null;
            /** Headline Outcome Text */
            headline_outcome_text: string | null;
            /** Category Of Concern */
            category_of_concern: string | null;
        };
        /** SchoolProfileOfstedTimelineResponse */
        SchoolProfileOfstedTimelineResponse: {
            /** Events */
            events: components["schemas"]["SchoolProfileOfstedTimelineEventResponse"][];
            coverage: components["schemas"]["SchoolProfileOfstedTimelineCoverageResponse"];
        };
        /** SchoolProfilePerformanceResponse */
        SchoolProfilePerformanceResponse: {
            latest: components["schemas"]["SchoolProfilePerformanceYearResponse"] | null;
            /** History */
            history?: components["schemas"]["SchoolProfilePerformanceYearResponse"][];
        };
        /** SchoolProfilePerformanceYearResponse */
        SchoolProfilePerformanceYearResponse: {
            /** Academic Year */
            academic_year: string;
            /** Attainment8 Average */
            attainment8_average: number | null;
            /** Progress8 Average */
            progress8_average: number | null;
            /** Progress8 Disadvantaged */
            progress8_disadvantaged: number | null;
            /** Progress8 Not Disadvantaged */
            progress8_not_disadvantaged: number | null;
            /** Progress8 Disadvantaged Gap */
            progress8_disadvantaged_gap: number | null;
            /** Engmath 5 Plus Pct */
            engmath_5_plus_pct: number | null;
            /** Engmath 4 Plus Pct */
            engmath_4_plus_pct: number | null;
            /** Ebacc Entry Pct */
            ebacc_entry_pct: number | null;
            /** Ebacc 5 Plus Pct */
            ebacc_5_plus_pct: number | null;
            /** Ebacc 4 Plus Pct */
            ebacc_4_plus_pct: number | null;
            /** Ks2 Reading Expected Pct */
            ks2_reading_expected_pct: number | null;
            /** Ks2 Writing Expected Pct */
            ks2_writing_expected_pct: number | null;
            /** Ks2 Maths Expected Pct */
            ks2_maths_expected_pct: number | null;
            /** Ks2 Combined Expected Pct */
            ks2_combined_expected_pct: number | null;
            /** Ks2 Reading Higher Pct */
            ks2_reading_higher_pct: number | null;
            /** Ks2 Writing Higher Pct */
            ks2_writing_higher_pct: number | null;
            /** Ks2 Maths Higher Pct */
            ks2_maths_higher_pct: number | null;
            /** Ks2 Combined Higher Pct */
            ks2_combined_higher_pct: number | null;
        };
        /** SchoolProfileResponse */
        SchoolProfileResponse: {
            school: components["schemas"]["SchoolProfileSchoolResponse"];
            demographics_latest: components["schemas"]["SchoolProfileDemographicsLatestResponse"] | null;
            performance: components["schemas"]["SchoolProfilePerformanceResponse"] | null;
            ofsted_latest: components["schemas"]["SchoolProfileOfstedLatestResponse"] | null;
            ofsted_timeline: components["schemas"]["SchoolProfileOfstedTimelineResponse"];
            area_context: components["schemas"]["SchoolProfileAreaContextResponse"];
            completeness: components["schemas"]["SchoolProfileCompletenessResponse"];
        };
        /** SchoolProfileSchoolResponse */
        SchoolProfileSchoolResponse: {
            /** Urn */
            urn: string;
            /** Name */
            name: string;
            /** Phase */
            phase: string | null;
            /** Type */
            type: string | null;
            /** Status */
            status: string | null;
            /** Postcode */
            postcode: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** SchoolProfileSectionCompletenessResponse */
        SchoolProfileSectionCompletenessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "partial" | "unavailable";
            /** Reason Code */
            reason_code: ("source_missing" | "insufficient_years_published" | "source_not_in_catalog" | "source_file_missing_for_year" | "source_schema_incompatible_for_year" | "partial_metric_coverage" | "source_not_provided" | "rejected_by_validation" | "not_joined_yet" | "pipeline_failed_recently" | "not_applicable" | "source_coverage_gap" | "stale_after_school_refresh" | "no_incidents_in_radius") | null;
            /** Last Updated At */
            last_updated_at: string | null;
            /** Years Available */
            years_available?: string[] | null;
        };
        /** SchoolSearchItemResponse */
        SchoolSearchItemResponse: {
            /** Urn */
            urn: string;
            /** Name */
            name: string;
            /** Type */
            type: string | null;
            /** Phase */
            phase: string | null;
            /** Postcode */
            postcode: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Distance Miles */
            distance_miles: number;
        };
        /** SchoolTrendPointResponse */
        SchoolTrendPointResponse: {
            /** Academic Year */
            academic_year: string;
            /** Value */
            value: number | null;
            /** Delta */
            delta: number | null;
            /** Direction */
            direction: ("up" | "down" | "flat") | null;
        };
        /** SchoolTrendsCompletenessResponse */
        SchoolTrendsCompletenessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "partial" | "unavailable";
            /** Reason Code */
            reason_code: ("source_missing" | "insufficient_years_published" | "source_not_in_catalog" | "source_file_missing_for_year" | "source_schema_incompatible_for_year" | "partial_metric_coverage" | "source_not_provided" | "rejected_by_validation" | "not_joined_yet" | "pipeline_failed_recently" | "not_applicable") | null;
            /** Last Updated At */
            last_updated_at: string | null;
            /** Years Available */
            years_available?: string[] | null;
        };
        /** SchoolTrendsHistoryQualityResponse */
        SchoolTrendsHistoryQualityResponse: {
            /** Is Partial History */
            is_partial_history: boolean;
            /** Min Years For Delta */
            min_years_for_delta: number;
            /** Years Count */
            years_count: number;
        };
        /** SchoolTrendsResponse */
        SchoolTrendsResponse: {
            /** Urn */
            urn: string;
            /** Years Available */
            years_available: string[];
            history_quality: components["schemas"]["SchoolTrendsHistoryQualityResponse"];
            series: components["schemas"]["SchoolTrendsSeriesResponse"];
            completeness: components["schemas"]["SchoolTrendsCompletenessResponse"];
        };
        /** SchoolTrendsSeriesResponse */
        SchoolTrendsSeriesResponse: {
            /** Disadvantaged Pct */
            disadvantaged_pct: components["schemas"]["SchoolTrendPointResponse"][];
            /** Sen Pct */
            sen_pct: components["schemas"]["SchoolTrendPointResponse"][];
            /** Ehcp Pct */
            ehcp_pct: components["schemas"]["SchoolTrendPointResponse"][];
            /** Eal Pct */
            eal_pct: components["schemas"]["SchoolTrendPointResponse"][];
            /** First Language English Pct */
            first_language_english_pct: components["schemas"]["SchoolTrendPointResponse"][];
            /** First Language Unclassified Pct */
            first_language_unclassified_pct: components["schemas"]["SchoolTrendPointResponse"][];
        };
        /** SchoolsSearchCenterResponse */
        SchoolsSearchCenterResponse: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** SchoolsSearchQueryResponse */
        SchoolsSearchQueryResponse: {
            /** Postcode */
            postcode: string;
            /** Radius Miles */
            radius_miles: number;
        };
        /** SchoolsSearchResponse */
        SchoolsSearchResponse: {
            query: components["schemas"]["SchoolsSearchQueryResponse"];
            center: components["schemas"]["SchoolsSearchCenterResponse"];
            /** Count */
            count: number;
            /** Schools */
            schools: components["schemas"]["SchoolSearchItemResponse"][];
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Title */
            title: string;
        };
        /** TaskResponse */
        TaskResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_schools_api_v1_schools_get: {
        parameters: {
            query: {
                postcode: string;
                radius?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolsSearchResponse"];
                };
            };
            /** @description Invalid postcode or radius parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Postcode not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Postcode resolver unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_schools_by_name_api_v1_schools_search_get: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolNameSearchResponse"];
                };
            };
            /** @description Invalid name search parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_school_profile_api_v1_schools__urn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolProfileResponse"];
                };
            };
            /** @description School URN not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description School profile datastore unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_school_trends_api_v1_schools__urn__trends_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolTrendsResponse"];
                };
            };
            /** @description School URN not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description School trends datastore unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
