/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Schools */
        get: operations["search_schools_api_v1_schools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{urn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get School Profile */
        get: operations["get_school_profile_api_v1_schools__urn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SchoolProfileDemographicsCoverageResponse */
        SchoolProfileDemographicsCoverageResponse: {
            /** Fsm Supported */
            fsm_supported: boolean;
            /** Ethnicity Supported */
            ethnicity_supported: boolean;
            /** Top Languages Supported */
            top_languages_supported: boolean;
        };
        /** SchoolProfileDemographicsLatestResponse */
        SchoolProfileDemographicsLatestResponse: {
            /** Academic Year */
            academic_year: string;
            /** Disadvantaged Pct */
            disadvantaged_pct: number | null;
            /** Fsm Pct */
            fsm_pct: number | null;
            /** Sen Pct */
            sen_pct: number | null;
            /** Ehcp Pct */
            ehcp_pct: number | null;
            /** Eal Pct */
            eal_pct: number | null;
            /** First Language English Pct */
            first_language_english_pct: number | null;
            /** First Language Unclassified Pct */
            first_language_unclassified_pct: number | null;
            coverage: components["schemas"]["SchoolProfileDemographicsCoverageResponse"];
        };
        /** SchoolProfileOfstedLatestResponse */
        SchoolProfileOfstedLatestResponse: {
            /** Overall Effectiveness Code */
            overall_effectiveness_code: string | null;
            /** Overall Effectiveness Label */
            overall_effectiveness_label: string | null;
            /** Inspection Start Date */
            inspection_start_date: string | null;
            /** Publication Date */
            publication_date: string | null;
            /** Is Graded */
            is_graded: boolean;
            /** Ungraded Outcome */
            ungraded_outcome: string | null;
        };
        /** SchoolProfileResponse */
        SchoolProfileResponse: {
            school: components["schemas"]["SchoolProfileSchoolResponse"];
            demographics_latest: components["schemas"]["SchoolProfileDemographicsLatestResponse"] | null;
            ofsted_latest: components["schemas"]["SchoolProfileOfstedLatestResponse"] | null;
        };
        /** SchoolProfileSchoolResponse */
        SchoolProfileSchoolResponse: {
            /** Urn */
            urn: string;
            /** Name */
            name: string;
            /** Phase */
            phase: string | null;
            /** Type */
            type: string | null;
            /** Status */
            status: string | null;
            /** Postcode */
            postcode: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** SchoolSearchItemResponse */
        SchoolSearchItemResponse: {
            /** Urn */
            urn: string;
            /** Name */
            name: string;
            /** Type */
            type: string | null;
            /** Phase */
            phase: string | null;
            /** Postcode */
            postcode: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Distance Miles */
            distance_miles: number;
        };
        /** SchoolsSearchCenterResponse */
        SchoolsSearchCenterResponse: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** SchoolsSearchQueryResponse */
        SchoolsSearchQueryResponse: {
            /** Postcode */
            postcode: string;
            /** Radius Miles */
            radius_miles: number;
        };
        /** SchoolsSearchResponse */
        SchoolsSearchResponse: {
            query: components["schemas"]["SchoolsSearchQueryResponse"];
            center: components["schemas"]["SchoolsSearchCenterResponse"];
            /** Count */
            count: number;
            /** Schools */
            schools: components["schemas"]["SchoolSearchItemResponse"][];
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Title */
            title: string;
        };
        /** TaskResponse */
        TaskResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_schools_api_v1_schools_get: {
        parameters: {
            query: {
                postcode: string;
                radius?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolsSearchResponse"];
                };
            };
            /** @description Invalid postcode or radius parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Postcode not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Postcode resolver unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_school_profile_api_v1_schools__urn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolProfileResponse"];
                };
            };
            /** @description School URN not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description School profile datastore unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
